name: eval_dual_flow
task_name: "eval/dual_flow"
tags: ["eval", "dual_flow"]
split: test
eval_mode: predict
ckpt_path: ${ckpt.dual_flow}
eval_sampling_temperature: 0.5
eval_sample_without_replacement: true
dataset_variants:
  - ${dataset.dataset_family}
  - ${dataset.dataset_family}-sub
