# @package trainer

_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}
accelerator: cpu
devices: 1
precision: 32-true

min_epochs: 0
max_epochs: -1
max_steps: 100000

accumulate_grad_batches: 1
gradient_clip_val: null
gradient_clip_algorithm: norm
benchmark: false
val_check_interval: null
check_val_every_n_epoch: 1
use_distributed_sampler: false
num_sanity_val_steps: 0

limit_train_batches: null
limit_val_batches: null
limit_test_batches: null

log_every_n_steps: 50
deterministic: false
enable_checkpointing: true
enable_model_summary: false
enable_progress_bar: true
detect_anomaly: false
