# @package trainer

_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}
accelerator: gpu
devices: 1
precision: bf16-mixed
strategy: auto

max_epochs: 10000

max_steps: -1

benchmark: true

val_check_interval: null
check_val_every_n_epoch: 1
use_distributed_sampler: false
num_sanity_val_steps: 2

limit_train_batches: null
limit_val_batches: null
limit_test_batches: null

log_every_n_steps: 10
deterministic: false
enable_checkpointing: true
enable_model_summary: false
enable_progress_bar: true
detect_anomaly: false

gradient_clip_val: null
gradient_clip_algorithm: norm