# @package model.training_cfg

defaults:
  - _self_
  - sampling_temperature_schedule: default
  - action_pruning: default
  - answer_reward: default
  - subtb: default
  - auxiliary: default

rollouts_per_graph: 8
sampling_temperature: 1.0
