# @package hydra

defaults:
  - override hydra_logging: default
  - override job_logging: default

run:
  dir: ${paths.run_dir}

sweep:
  dir: ${paths.output_dir}/multirun/${task_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job:
  chdir: false

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
