defaults:
  - _self_
  - gflownet/horizon_cfg: default
  - gflownet/training_cfg: default
  - gflownet/policy_cfg: default
  - gflownet/eval_cfg: default
  - gflownet/optimizer_cfg: default
  - gflownet/scheduler_cfg: default

_target_: src.models.gflownet_module.GFlowNetModule
_recursive_: true
_convert_: all

metric_runtime_factory:
  _target_: src.metrics.runtime_factory.GraphTaskRuntimeFactory
