defaults:
  - weaver
  - _self_

rollout_cfg:
  coverage_num_rollout: 2


coverage_cfg:
  enabled: true
  path_count_tiebreak_weight: 0.0
  
schedule_cfg:
  proposal_cfg:
    enabled: true
    warmup_steps: 100
    decay_steps: 300
    initial_prob: 0.95
    final_prob: 0.05
    allow_nonzero_final_prob: true
