# configs/dataset/cwq.yaml

defaults:
  - base
  - _self_

name: cwq
dataset_scope: full
dataset_family: cwq
max_steps: 10
hf_dataset: rmanluo/RoG-cwq

train_samples_per_epoch: 2048

filter_missing_answer:
  train: false
  validation: false
  test: false

q_entity_blacklist:
  - Country
  - US State
  - College/University
  - UK constituent country
  - Film
  - Male
  - Marriage
  - United States Senator
  - United States Senate
