# @package dataset

name: cwq
dataset_family: kgqa
dataset_scope: cwq
dataset_source: hf
hf_dataset: rmanluo/RoG-cwq
hf_revision: b0f6275586286312c4e99ef4b0adc65463c91f8e

entity_typing:
  non_text_prefixes: ["m.", "g."]

splits:
  train: train
  validation: validation
  test: test

root_dir: ${paths.data_dir}/${dataset.name}
artifact_dir: ${dataset.root_dir}/artifacts

paths:
  raw_dir: ${dataset.root_dir}/raw
  metadata_dir: ${dataset.root_dir}/metadata
  embeddings_dir: ${dataset.root_dir}/embeddings

column_map:
  question_id_field: id
  question_field: question
  answer_text_field: answer
  question_entity_field: q_entity
  answer_entity_field: a_entity
  graph_field: graph
