# @package dataset

name: webqsp
dataset_family: kgqa
dataset_scope: webqsp
dataset_source: hf
hf_dataset: rmanluo/RoG-webqsp

splits:
  train: train
  validation: validation
  test: test

root_dir: ${paths.data_dir}/${dataset.name}
artifact_dir: ${dataset.root_dir}/artifacts

paths:
  raw_dir: ${dataset.root_dir}/raw
  lmdb_dir: ${dataset.root_dir}/lmdb
  metadata_dir: ${dataset.root_dir}/metadata
  embeddings_dir: ${dataset.root_dir}/embeddings
  entity_text_embeddings: ${dataset.paths.embeddings_dir}/entity_text_embeddings.pt
  relation_embeddings: ${dataset.paths.embeddings_dir}/relation_embeddings.pt
  entity_metadata_path: ${dataset.paths.metadata_dir}/entity_metadata.pt
  entity_catalog_path: ${dataset.paths.metadata_dir}/entity_catalog.pt
  relation_catalog_path: ${dataset.paths.metadata_dir}/relation_catalog.pt

column_map:
  question_id_field: id
  question_field: question
  answer_text_field: answer
  question_entity_field: q_entity
  answer_entity_field: a_entity
  graph_field: graph
