# @package paths

root_dir: ${oc.env:PROJECT_ROOT,${oc.env:PWD}}
data_dir: ${oc.env:DATA_DIR,${paths.root_dir}/data}
output_dir: ${paths.root_dir}/outputs

run_dir: ${paths.output_dir}/${task_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
log_dir: ${paths.run_dir}/logs
ckpt_dir: ${paths.run_dir}/checkpoints
artifact_dir: ${paths.run_dir}/artifacts

hf_home: ${oc.env:HF_HOME,${paths.root_dir}/.cache/huggingface}
hf_datasets_cache: ${oc.env:HF_DATASETS_CACHE,${paths.hf_home}/datasets}
cache_dir: ${paths.hf_home}
work_dir: ${hydra:runtime.cwd}