# Default training callback bundle.
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-step_{step:07d}"
  monitor: "val/high_reward/oracle_max_recall@4"
  save_top_k: 3
  save_last: true
  mode: max
  every_n_epochs: 1
  every_n_train_steps: null
  save_on_train_epoch_end: false

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/high_reward/oracle_max_recall@4"
  min_delta: 0.001
  patience: 10
  verbose: true
  mode: max
  strict: true
  check_finite: True

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: -1

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar