# configs/preprocess.yaml

defaults:
  - _self_
  - paths: default
  - dataset: null  # 强制要求命令行传入 dataset=XXX
  - pipeline: default
  - hydra: default

task_name: preprocess

pipeline_stage: all
progress_bar: true

encoder:
  model_name: Alibaba-NLP/gte-large-en-v1.5
  device: auto
  precision: bf16
  batch_size: 512
  reuse_embeddings_if_exists: false

hf_env:
  cache_dir: ${paths.hf_datasets_cache}
  offline: false