# @package _global_

defaults:
  - paths: default
  - hydra: default
  - dataset: webqsp
  - datamodule: default
  - model: weaver
  - trainer: gpu
  - callbacks: train
  - logger: wandb
  - ckpt: default
  - _self_
  - profiler: null
  - experiment: null

task_name: train
seed: 42
print_config: false
test_after_fit: true
profiler: null

fit_ckpt_path: ${ckpt.fit}
pretrained_ckpt_path: ${ckpt.pretrained}
strict_pretrained_load: ${ckpt.strict_pretrained_load}
